name: Deploy
on:
  release:
    types: [published]
jobs:
  DEPLOY:
    name: GitHub and Maven Central publication
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GHUB_USER: ${{ secrets.GHUB_USER }}
      GHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GHUB_PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Publish to Maven Central
        run: ./gradlew deployNexus
      - name: Publish to GitHub Packages
        run: ./gradlew deployGithub
